from sc.utils import Reader, Writer



HAS_EXTERENAL_HIGHRES_TEX_FILE_TAG = 23
HAS_EXTERENAL_TEX_FILE_TAG = 26
HAS_EXTERENAL_LOWRES_TEX_FILE_TAG = 30

SWFTEXTURE_TAG = 1
SWFTEXTURE2_TAG = 16
SWFTEXTURE3_TAG = 19
SWFTEXTURE4_TAG = 24
SWFTEXTURE_TILED_TAG = 27
SWFTEXTURE_TILED2_TAG = 28
SWFTEXTURE5_TAG = 29
SWFTEXTURE6_TAG = 34

MOVIE_CLIP_MODIFIERS_TAG = 37
MOVIE_CLIP_MODIFIER_TAG = 38
MOVIE_CLIP_MODIFIER2_TAG = 39
MOVIE_CLIP_MODIFIER3_TAG = 40

SHAPE_TAG = 2
SHAPE2_TAG = 18

SHAPE_DRAW_BITMAP_COMMAND_TAG = 4
SHAPE_DRAW_COLOR_FILL_COMMAND_TAG = 6
SHAPE_DRAW_BITMAP2_COMMAND_TAG = 17
SHAPE_DRAW_BITMAP3_COMMAND_TAG = 22

TEXT_FIELD_TAG = 7
TEXT_FIELD2_TAG = 15
TEXT_FIELD3_TAG = 20
TEXT_FIELD4_TAG = 21
TEXT_FIELD5_TAG = 25
TEXT_FIELD6_TAG = 33
TEXT_FIELD7_TAG = 44

TRANSFORMS_STORAGE_TAG = 42

MATRIX2X3_TAG = 8
COLOR_TRANSFORM_TAG = 9

MOVIE_CLIP_TAG = 3
MOVIE_CLIP2_TAG = 10
MOVIE_CLIP3_TAG = 12
MOVIE_CLIP4_TAG = 14
MOVIE_CLIP5_TAG = 35

MOVIE_CLIP_FRAME_TAG = 5
MOVIE_CLIP_FRAME2_TAG = 11
MOVIE_CLIP_SCALING_GRID_TAG = 31
MOVIE_CLIP_TRANSFORMS_STORAGE_TAG = 41

END_TAG = 0


class Tag(Reader, Writer):
    def __init__(self, tag: int = 0) -> None:
        self.tag = tag
    
    def load(self, data: bytes):
        Reader.__init__(self, data)
    
    def save(self):
        Writer.__init__(self)
